"""Initial migration with Patient model

Revision ID: 37396702cee8
Revises: 
Create Date: 2025-06-18 22:06:53.993069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '37396702cee8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('family_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('given_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('family_name_kana', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('given_name_kana', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNKNOWN', name='genderenum'), nullable=False),
    sa.Column('blood_type', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', 'UNKNOWN', name='bloodtypeenum'), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('prefecture', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('emergency_contact_relationship', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('allergies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medical_history', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_medications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('insurance_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('insurance_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_patient_number'), 'patient', ['patient_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_patient_number'), table_name='patient')
    op.drop_table('patient')
    # ### end Alembic commands ###
